[project]
name = "reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "html2text>=2025.4.15",
    "naked>=0.1.32",
]

[tool.pyright]
venvPath = "."
venv = "venv"
pythonVersion = "3.13"
